source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!
xcodeproj 'MyMobileApp.xcodeproj'

target 'MyMobileApp' do
  pod 'LongPressRecordButton'
  pod 'JPSVolumeButtonHandler'
  pod 'BSImagePicker', '~> 2.2'
end
