source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!
xcodeproj 'Cartoon View.xcodeproj'

target 'Cartoon View' do
  pod 'LongPressRecordButton'
  pod 'WPMediaPicker'
end
